name: pgf
description: "Gif app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  bitsdojo_window: ^0.1.6
  window_manager: ^0.4.3
  system_tray: ^2.0.3
  shared_preferences: ^2.5.2
  event_bus: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
